### ISSUE TITLE
Which licence to use? 

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine_configurator#1]
We want a permissive licence for this app so that ideally people can just take and reuse and repackage. Our standard LGPL 2.1 is probably not appropriate.

Do you agree? Suggestions @sergiocontrino @yochannah?

**Comment by yochannah** [comment]
revisiting this - the repo currently has GPL which is strongly copylefted (non-permissive). I think we should relicence to MIT or Apache for better permissiveness.

**Comment by yochannah** [comment]
Okay, I just chatted with @sergiocontrino and he agrees it's okay to migrate to a more permissive licence. My understanding of software relicencing rules is that generally you should have permission from most or ideally all contributors. 

Dear @julie-sullivan and @leoank, as the other contributors on this repo who aren't me - could you please confirm that you're okay with moving to Apache?

**Comment by leoank** [comment]
I'm okay with moving to Apache.

**Comment by julie-sullivan** [comment]
That is fine.

**Comment by yochannah** [comment]
Thanks so much, both!
