### ISSUE TITLE
do we need fileLocation?

### ISSUE THREAD

**Issue by intermineorg** [intermine/intermine_configurator#11]
@leoank 

ON CLOUD - we are using the pattern `$IM_DATA_DIR/$user_id/$source_id/`
LOCALLY - files will stay on local drive. sym link from real file to `$IM_DATA_DIR/$user_id/$source_id/`

Is that right? So I should remove `fileLocation` from end point in configurator?

**Comment by leoank** [comment]
On cloud, we are using the pattern `$IM_DATA_DIR/$user_id/$mine_id/data/$source_id/` for data files
and `$IM_DATA_DIR/$user_id/$mine_id/configs/`.
Same for local installs too.
And yes, you can remove fileLocation from the endpoint

**Comment by julie-sullivan** [comment]
no we don't!

These updates are made.
