### ISSUE TITLE
fileId --> directoryId

### ISSUE THREAD

**Issue by intermineorg** [intermine/intermine_configurator#12]
@yochannah @leoank We have the idea of a file. When a user uploads a file, they annotate it with some metadata, then that file is loaded into InterMine. We pass a `fileId` back and forth to represent this file. 

Right now there is a one to one relationship. Eventually (one beautiful day), we'll have multiple files per data source. 

Do you think it's worth introducing the idea of a `directoryId` or `sourceId` or similar which represents the data source itself?

**Comment by leoank** [comment]
That makes sense. 
 - But then the user has to select this source or directory before uploading any data files. 
 - We need to make changes in `/data/upload` and `/data/upload/remote` compose API too. 
 - Wizard also needs to be updated. 
 - Wizard will probably need an API to list directories to the user.
 - How we will name directories ( right now we are naming them using the first file name)?
 - Does this affect the config creation process?

**Comment by julie-sullivan** [comment]
> But then the user has to select this source or directory before uploading any data files.
I wouldn't want anything visible to the user.

**Comment by leoank** [comment]
In that case, how we are going to decide that which file belongs to which directory?

**Comment by julie-sullivan** [comment]
the wizard would control this.

**Comment by leoank** [comment]
maybe I am missing something, but how wizard will handle this? I don't think we can do this without changing our API. Also in any scenario we cannot always predict the directory for a file (or can we?), So we are going to need user input.

**Comment by julie-sullivan** [comment]
because a file != a data source. There isn't a one to one relationship between files and data sources.

For example, GFF is a file format. A user can configure this data source, and have uploaded two data files.

FASTA is a file format. A user can configure this data source via the wizard, and have uploaded two files.

There isn't a one to one relationship between files and data sources. (In InterMine, this is almost never true.)

**Comment by julie-sullivan** [comment]
I was thinking the directory could be `fasta1` or a UUID. The user will not be involved.

Needs more thought!

**Comment by leoank** [comment]
Okay, got it. So we can infer directory using the file extension. We can name the directories based on file extensions. We don’t have to worry about name collisions here, as we already know the number of file extensions we support.

**Comment by julie-sullivan** [comment]
okay @yochannah says this is premature optimisation, and we should get the processing of one file done before we worry about multiple files.
