### ISSUE TITLE
/mine/config -- what is needed?

### ISSUE THREAD

**Issue by intermineorg** [intermine/intermine_configurator#13]
@yochannah what do you need for the `GET /mine/config` end point?

There are two concepts: 

* the choices the user is making as she is going through the wizard.
* the config needed to build a mine.

the former informs the latter.

Maybe we need:

`/mine/config/` - all the choices the user made
`/mine/config/generate` - the project XML, list of tools, and data model file needed to build an intermine.

Can you confirm?

**Comment by intermineorg** [comment]
What do we need `/mine/config` for? If it's to populate the wizard so a user can edit their responses, we already have end points for that.

Maybe worth examining?

**Comment by julie-sullivan** [comment]
`/mine/user-config` - the answers the user supplied to the wizard
`/mine/build-config` - the files needed (by intermine-compose) to run a build. (project XML, data model and list of tools

**Comment by julie-sullivan** [comment]
also a new end point with the answers for the file. Needs `fileId`!

* fileName
* organism
* array of questions with selected answers

**Comment by julie-sullivan** [comment]
Is it confusing that `DELETE /mine/user-config` is deleting:

`/mine/build-config`
`/mine/supplementarysources`
`/mine/datatools`

Maybe I should rename to `/mine/user-config/supplementarysources` and `/mine/user-config/datatools`?

**Comment by julie-sullivan** [comment]
this is fixed now.
