### ISSUE TITLE
Questions on the Upload confirmation page -- do we want headers with the response?

### ISSUE THREAD

**Issue by intermineorg** [intermine/intermine_configurator#14]
https://yochannah.github.io/wizard/3-upload-complete-fasta.html

1. top section with the preview, you have "header" and "sequence". Those aren't generic headers. Do you want those in the response? Or do we want to select a generic header?

2. attributes of the file are not in the API yet. We have `rowCount` but not record count. In the future they may be custom info for files. maybe make this just an array of values?

3. the Q&As have a nice bolded header. But i think in the API we just have the question ID and question text. Should we add a question header?

**Comment by julie-sullivan** [comment]
yes we do! 

this is done now.
