### ISSUE TITLE
fat JAR is not working

### ISSUE THREAD

**Issue by leoank** [intermine/intermine_configurator#19]
I am getting this error message
```
[main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
```
I also tried copying the application.properties file to the runtime container and use this command to start the server:
```
java -jar -Dspring.config.location=/intermine/app.properties /intermine/intermine-configurator.jar
```
but it is still not working.

**Comment by julie-sullivan** [comment]
fixed by #17. Can you do a pull and try again?

This worked for me:

```
julie ~/git/intermine-configurator $ ./gradlew createUberJar

```

Then the JAR with the compiled files and the libs is here:

```
./build/libs/intermine-configurator-uber-0.1.0.jar
```

**Comment by leoank** [comment]
this command will work to launch the server?
```
java -jar  ./build/libs/intermine-configurator-uber-0.1.0.jar
```
or `-Dspring.config.location` flag is still needed?

**Comment by julie-sullivan** [comment]
This works: `java -jar ./build/libs/intermine-configurator-0.1.0.jar`
