### ISSUE TITLE
Location for data files is not correct

### ISSUE THREAD

**Issue by leoank** [intermine/intermine_configurator#38]
compose is using the location: ` $IM_DATA_DIR/$USER_ID/data/$FILE_ID`
and configurator is looking for the file at `$IM_DATA_DIR/$USER_ID/$MINE_ID/$FILE_ID`

file is uploaded without a mineID. So, compose cannot use the path that configurator is using right now.

**Comment by julie-sullivan** [comment]
The code looks correct to me: https://github.com/intermine/intermine_configurator/blob/master/src/main/java/org/intermine/configurator/DataFileManager.java#L116

**Comment by leoank** [comment]
compose is saving file at `$IM_DATA_DIR/$USER_ID/data/$FILE_ID` and the path that is being constructed by configurator is `$IM_DATA_DIR/$USER_ID/$FILE_ID/$FILE_NAME`. You are missing `data` in the path and also adding extra `$FILE_NAME` var. Do you want me to change the path structure?

**Comment by julie-sullivan** [comment]
oh i didn't see the `data` part! Yes, please update. :)

**Comment by leoank** [comment]
storing files with user provided filenames can be tricky.. So is it okay if I update compose to use `$IM_DATA_DIR/$USER_ID/$FILE_ID`?

**Comment by julie-sullivan** [comment]
yes, that's safe to change to wherever the file will be! :)

**Comment by yochannah** [comment]
@sergiocontrino when you have a chance can we chat about this? It's a blocker for the wizard

**Comment by sergiocontrino** [comment]
@yochannah changed path to conform to im_compose according to the comments above. we can change path (rm the "data" dir) later in case.

**Comment by yochannah** [comment]
Can confirm this is now fixed - thanks @sergiocontrino !
